# Generated by Django 2.2.28 on 2025-03-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voteType',
            field=models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4),
        ),
    ]
