# Generated by Django 2.2.28 on 2025-03-19 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile1',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile1',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
