# Generated by Django 2.2.28 on 2025-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('releaseDate', models.CharField(max_length=255)),
            ],
        ),
    ]
