# Generated by Django 2.2.28 on 2025-03-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=255)),
                ('albumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Album')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile1')),
            ],
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('userID', 'albumID'), name='uniqueVoteID'),
        ),
    ]
