# Generated by Django 2.2.28 on 2025-03-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20250311_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=255)),
                ('genreDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(max_length=255)),
                ('albumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Album')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile1')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favoritealbum',
            constraint=models.UniqueConstraint(fields=('userID', 'albumID'), name='uniqueFavAlbumID'),
        ),
    ]
