# Generated by Django 2.2.28 on 2025-03-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20250311_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumname', models.CharField(max_length=255)),
                ('albumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Album')),
                ('genreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Genre')),
            ],
        ),
        migrations.AddConstraint(
            model_name='genrealbum',
            constraint=models.UniqueConstraint(fields=('genreID', 'albumID'), name='uniqueGenreAlbum'),
        ),
    ]
