# Generated by Django 2.2.28 on 2025-03-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20250311_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(max_length=255)),
                ('genreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Genre')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile1')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favoritegenre',
            constraint=models.UniqueConstraint(fields=('userID', 'genreID'), name='uniqueFavoriteGenre'),
        ),
    ]
